name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  server:
    name: Server - install & lint & test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install server deps
        run: npm ci

      - name: Run server lint (if any)
        run: npm run lint || echo "no lint"

      - name: Run server tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          # add test script in server/package.json (npm test)
          npm test || echo "No tests or tests failed"

  client:
    name: Client - install & build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install client deps
        run: npm ci

      - name: Run client lint
        run: npm run lint || echo "no lint"

      - name: Build client
        run: npm run build
